### ISSUE TITLE
makeTFfasta - type error

### ISSUE THREAD

**Issue by jmrussell** [TaliaferroLab/LABRAT#2]
After following the instructions for installation I get the following error when running makeTFfasta:

```
python ../LABRAT/LABRAT.py --mode makeTFfasta --gff /n/analysis/indexes/danRer11/annotation/Ens_98/gtfs/danRer11.Ens_98.gff --genomefasta /n/analysis/indexes/danRer11/danRer11.fa --librarytype RNAseq

```

```

Indexing gff...
Traceback (most recent call last):
  File "../LABRAT/LABRAT.py", line 835, in <module>
    makeTFfasta(args.gff, args.genomefasta, args.lasttwoexons)
  File "../LABRAT/LABRAT.py", line 255, in makeTFfasta
    db = gffutils.FeatureDB(db_fn)
  File "/home/jr2396/miniconda3/envs/labrat/lib/python3.6/site-packages/gffutils/interface.py", line 132, in __init__
    version, dialect = c.fetchone()
    TypeError: 'NoneType' object is not iterable
  ```

Package list:

```

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
argcomplete               1.12.2             pyhd3eb1b0_0
argh                      0.26.2                   py36_0
biopython                 1.78             py36h7b6447c_0
blas                      1.0                         mkl
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.1.19            h06a4308_0
certifi                   2020.12.5        py36h06a4308_0
gffutils                  0.9                        py_1    bioconda
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2020.2                      254
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
mkl                       2020.2                      256
mkl-service               2.3.0            py36he8ac12f_0
mkl_fft                   1.3.0            py36h54f3939_0
mkl_random                1.1.1            py36h0573a6f_0
ncurses                   6.2                  he6710b0_1
numpy                     1.19.2           py36h54aff64_0
numpy-base                1.19.2           py36hfa32c7d_0
openssl                   1.1.1j               h27cfd23_0
pandas                    1.0.5            py36h0573a6f_0
patsy                     0.5.1                    py36_0
pip                       21.0.1           py36h06a4308_0
pyfaidx                   0.5.9.5            pyh3252c3a_0    bioconda
python                    3.6.13               hdb3f193_0
python-dateutil           2.8.1              pyhd3eb1b0_0
pytz                      2021.1             pyhd3eb1b0_0
readline                  8.1                  h27cfd23_0
salmon                    0.14.2               ha0cc327_0    bioconda
scipy                     1.3.2            py36h7c811a0_0
setuptools                52.0.0           py36h06a4308_0
simplejson                3.8.1                    py36_0    bioconda
six                       1.15.0           py36h06a4308_0
sqlite                    3.33.0               h62c20be_0
statsmodels               0.10.1           py36hdd07704_0
tbb                       2020.3               hfd86e86_0
tk                        8.6.10               hbc83047_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3

```

I also get an error about the library type argument when it's included:

```

LABRAT.py: error: unrecognized arguments: --librarytype RNAseq

```

**Comment by jmrussell** [comment]
Issue with gff, using the zebrafish GTF I had resolved the problem

**Comment by taliaferrojm** [comment]
Interesting that the GTF solved the problem. I wouldn't have guessed that. We made a decision to be conservative with annotations, relying on flags within the annotation to throw out low-confidence isoforms. The problem with this is that those flags can vary depending on where you get the annotation from. The main script, LABRAT.py, is designed for GENCODE-style annotations, which are available for human and mouse. For other species, Ensembl-style annotations may work using either LABRAT_dm6 or LABRAT_rn5 which were made for Ensembl fly and rat annotations, respectively. Unfortunately, those scripts don't have all the features that LABRAT.py does (like the `librarytype` parameter, for example). That's on the to-do list though!  

If one of those works for you in regards to correctly dealing with the annotation, let me know and I will update them to include all the latest features.  If not, if you send me your (zebrafish?) annotation, I can write a version of LABRAT that will work with that specific annotation.

**Comment by jmrussell** [comment]
I think I closed this a little too soon. Sorry for the late response but it's been busy lately. So I did not generate this gtf, another collaborator did but from what I can tell it's in Ensembl-style but unfortunately neither the dm6 nor the rn5 scripts seem to work. If you're still willing, I would love to email you the gtf and have you take a look, otherwise I can take a shot at updating one of your scripts myself.

**Comment by taliaferrojm** [comment]
It's actually better the GTF didn't work because I would have been more confused if it did.  Go ahead and email me the gff (not GTF). Or if it's too big maybe like the first 1000 lines or something. I'll get to it hopefully soon.  Thanks!

**Comment by taliaferrojm** [comment]
OK check out LABRAT_danRer.py.  I was able to run `--makeTFfasta` mode and generate TFseqs.fa. There might (or might not) be problems in later steps, but I'm happy to address them as they come up.

Small side note: the genome I downloaded from Ensembl wasn't going to play well with this gff because the chromosome names were different. Running `sed 's/>/>chr/g' danRer.genome.fa | sed 's/ d.*$//' > danRer.genome.clean.fa` removed the junk in the chromosome names that Ensembl put in there.

**Comment by jmrussell** [comment]
I get this error when trying to run makeTFfasta:

import pandas.util.testing as tm
Indexing gff...
Traceback (most recent call last):
  File "LABRAT_danRer.py", line 878, in <module>
    makeTFfasta(args.gff, args.genomefasta, args.lasttwoexons,
args.librarytype)
  File "LABRAT_danRer.py", line 266, in makeTFfasta
    db = gffutils.FeatureDB(db_fn)
  File
"/home/jr2396/miniconda3/envs/labrat/lib/python3.6/site-packages/gffutils/interface.py",
line 132, in __init__
    version, dialect = c.fetchone()
TypeError: 'NoneType' object is not iterable


Oddly enough, the GTF will run but ends with a blank output so I'm not sure
what the issue with the GFF is. The genome file I'm using is formatted like
"chr#" until the end, where we get some wonky contigs like
""ChrUn_KZ116059v1"

**Comment by taliaferrojm** [comment]
Is there a file that ends with `.db` in the directory that contains your gff?  gffutils makes a db that it writes there so that you only have to index the gff once. However, if the indexing doesn't finish successfully, that file is still made, and then the next time you come along it tries to use that .db file. So if there is a file there, delete it and try again.

If that doesn't work, can you try running it on the 1000 line gff you sent me?

**Comment by jmrussell** [comment]
Ah, the 1000 line GFF works without issue. I think it's the mitochondrial
chr in my gff, it has a feature annotated as Mt_tRNA - that's my guess at
least. It seems to work if I remove those entries. Thank you again for your
prompt response.

**Comment by jmrussell** [comment]
I spoke a little too soon - even shaving off those lines gives an error,
though it is different:

File "LABRAT_danRer.py", line 878, in <module>
    makeTFfasta(args.gff, args.genomefasta, args.lasttwoexons,
args.librarytype)
  File "LABRAT_danRer.py", line 264, in makeTFfasta
    gffutils.create_db(gff_fn, db_fn, merge_strategy = 'merge', verbose =
True)
  File
"/home/jr2396/miniconda3/envs/labrat/lib/python3.6/site-packages/gffutils/create.py",
line 1288, in create_db
    c.create()
  File
"/home/jr2396/miniconda3/envs/labrat/lib/python3.6/site-packages/gffutils/create.py",
line 504, in create
    self._populate_from_lines(self.iterator)
  File
"/home/jr2396/miniconda3/envs/labrat/lib/python3.6/site-packages/gffutils/create.py",
line 585, in _populate_from_lines
    self._insert(f, c)
  File
"/home/jr2396/miniconda3/envs/labrat/lib/python3.6/site-packages/gffutils/create.py",
line 526, in _insert
    cursor.execute(constants._INSERT, feature.astuple())
sqlite3.InterfaceError: Error binding parameter 11 - probably unsupported
type.

**Comment by taliaferrojm** [comment]
Can you send me a link to your gff?

**Comment by jmrussell** [comment]
Here's the full gff

Jonathon

**Comment by taliaferrojm** [comment]
Was there supposed to be a link or attachment there?  I don't see anything. Apologies if I'm missing it.

**Comment by taliaferrojm** [comment]
OK I've narrowed down the offending line(s) to one of the unassembled chromosomes (chrUn...). I didn't narrow it down any more than that because my genome sequence file doesn't have those "chromosomes" anyway. So if you remove those lines from your gff (for example `grep -v chrUn`) it should work.

I really don't know what it is in one of those lines that is causing `gffutils` fits, but removing the unassembled chromosomes fixed the issue for me.

**Comment by jmrussell** [comment]
Awesome, I will give it a shot! I really can't thank you enough for your responsiveness.

**Comment by jmrussell** [comment]
I can make the .db file which looks to be the right size etc, but the TFseqs.fasta file is empty and so salmon fails

**Comment by taliaferrojm** [comment]
That sounds like an issue with your genome sequence file.  Are you sure the chromosome names in that file match the chromosome names in the gff?

**Comment by jmrussell** [comment]
yes, I pared down both files to have chr1-9 and chrM, they're formatted the same way and contain the exact same list of chr's but I still run into the same issue. Could you point me to the genome you used? I wonder if it's an issue with the way some of our annotations are generated at the institute I'm at.

**Comment by taliaferrojm** [comment]
I used a genome assembly from Ensembl (http://ftp.ensembl.org/pub/release-103/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna.primary_assembly.fa.gz). A trick here though is that the chromosome names don't match your gff. You can open the file and see that they are missing 'chr' and that they have a lot of extra junk too. I cleaned these using `sed 's/>/>chr/g' danRer.genome.fa | sed 's/ d.*$//' > danRer.genome.clean.fa` where `danRer.genome.fa` is the file you download.  I was able to make a `TFseqs.fa` file using your gff and this genome sequence.

Also, are you supplying a `--librarytype` parameter?

**Comment by jmrussell** [comment]
Here's what I ran -- danRer.genome.clean.fa is the primary assembly with fixed headers and danrer_head.gff is the first 1000 lines.

```
(labrat) python ../LABRAT_danRer.py --mode makeTFfasta --gff danrer_head.gff --genomefasta danRer.genome.clean.fa
/home/jr2396/miniconda3/envs/labrat/lib/python3.6/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
Indexing gff...
2021-03-19 14:25:19,606 - INFO - Populating features
2021-03-19 14:25:19,753 - INFO - Populating features table and first-order relations: 999 features
2021-03-19 14:25:19,754 - INFO - Updating relations
2021-03-19 14:25:19,808 - INFO - Creating relations(parent) index
2021-03-19 14:25:19,809 - INFO - Creating relations(child) index
2021-03-19 14:25:19,810 - INFO - Creating features(featuretype) index
2021-03-19 14:25:19,811 - INFO - Creating features (seqid, start, end) index
2021-03-19 14:25:19,811 - INFO - Creating features (seqid, start, end, strand) index
2021-03-19 14:25:19,812 - INFO - Running ANALYSE features
Done indexing!
Indexing genome sequence...
Done indexing!
(labrat) > ll -ht
total 3.5G
-rw-rw---- 1 jr2396 domain users    0 Mar 19 14:25 wholetranscriptseqs.fasta
-rw-rw---- 1 jr2396 domain users 668K Mar 19 14:25 danrer_head.gff.db
-rw-rw---- 1 jr2396 domain users 103K Mar 19 14:19 danrer_head.gff
-rw-rw---- 1 jr2396 domain users 1.4G Mar 18 13:09 danRer.genome.clean.fa
-rw-rw---- 1 jr2396 domain users 177M Dec 25 12:39 Danio_rerio.GRCz11.103.gff3
-rw-rw---- 1 jr2396 domain users 1.4G Dec 21 16:58 Danio_rerio.GRCz11.dna.primary_assembly.fa

**Comment by taliaferrojm** [comment]
OK yeah `--librarytype` is required. If you don't use that parameter, you will get an empty fasta file.  The allowed values are 'RNAseq' and '3pseq'. This is a new feature, so it's probably worth me making that clearer and preventing the code from running without it.

I would also recommend you use the `--lasttwoexons` flag, especially for a transcriptome like zebrafish whose assembly might not be as reliable as, say, human and mouse. This isn't required though.

**Comment by jmrussell** [comment]
Ok, I think the issue has been completely resolved. I think gffutils has an issue parsing chr with an '_' in them (or possibly any non-alphanumeric character), so once I removed the '_' in the gff and genome fasta step 1 worked without issue. From there, your program works beautifully when I remember to include the arguments required to make it work :). Thanks for your help.

**Comment by taliaferrojm** [comment]
Ah, glad you were able to figure it out!  Please don't hesitate to reach out if you run into any more issues.
