### ISSUE TITLE
makeTFfasta - UnboundLocalError

### ISSUE THREAD

**Issue by qianzhao613** [TaliaferroLab/LABRAT#7]
Hi,

When I tried to use makeTFfast to build an index, I used the following command:

```bash
# activate env
source activate labrat
# input
genomegff="~/reference/genes/genes.gtf"
genomeseq="~/reference/fasta/genome.fa"

LABRAT.py --mode makeTFfasta --gff ${genomegff} --genomefasta ${genomeseq} --librarytype 3pseq
```

Since I tried to build an index for 3' tagged-sequencing, I didn't add the --lasttwoexon parameter, and then the UnboundLocalError raised: `UnboundLocalError: local variable 'TFseq' referenced before assignment`

I checked the source code, and I guess the problem is when not using --lasttwoexon parameter, there is no TFseq variable assigned before the conditional statement (the variable used here is seq not TFseq,  shown below).

<img width="760" alt="1685896918645" src="https://github.com/TaliaferroLab/LABRAT/assets/55712358/4ff6f018-9b6f-4007-afe8-0f00165ab12c">

I'll try modifying the variable locally to verify it, please correct me if I'm wrong.

Best,
Qian

**Comment by taliaferrojm** [comment]
Hi Qian,

Yes, you are correct. Thanks for catching this error. 

`LABRAT.py` in the repository has been updated, but please note that this has not yet been pushed to `conda`.
